# EDA LH_NAUTICA
notebook tem como objetivo fazer a analise exploratoria dos dados disponibilizados de maneira didatica e transparente.

_________________________________________________________________________________________________________

## Objetivos 
* Como estão os dados brutos?
* O que precisa ser consertado no staging?
* Quais colunas precisam ser normalizadas?
* Quais chaves funcionam (ou não)?
* Há duplicações?
* Há dados faltantes?

## 1. Conexão com o Postgres

In [17]:

import pandas as pd
from sqlalchemy import create_engine

user="postgres"
password="postgres"
port=5433

engine = create_engine(f"postgresql://{user}:{password}@localhost:{port}/target_db")

df_clientes = pd.read_sql("SELECT * FROM clientes_crm", engine)
df_custos = pd.read_sql("SELECT * FROM custos_importacao", engine)
df_produtos = pd.read_sql("SELECT * FROM produtos_raw", engine)
df_vendas = pd.read_sql("SELECT * FROM vendas_2023_2024", engine)

## 2. EDA clientes
__________________________________________________________________________________

In [6]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   code       49 non-null     int64
 1   email      49 non-null     str
 2   full_name  49 non-null     str
 3   location   49 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.7 KB

In [10]:
df_clientes.duplicated().sum()

np.int64(0)

In [13]:
df_clientes

,code,email,full_name,location
0,1,femininos.oliveira.antunes@icloud.com,Femininos Oliveira Antunes,"Aratu (Candeias) , BA"
1,2,nunes.fernanda.soares.azevedo.vieira@outlook.com,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife"
2,3,farias.teixeira.daniel.ribeiro#gmail.com,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS"
3,4,thiago.moreira#gmail.com,Thiago Moreira,"AC , Rio Branco"
4,5,pedro.freitas#icloud.com,Pedro Freitas,PA - Santarém Novo
5,6,coelho.pinheiro.peixoto.antônia.cavalcanti@aol...,Antônia Coelho Pinheiro Peixoto Cavalcanti,"Fortaleza do Tabocão , TO"
6,7,torres.barros.rocha.bianca.siqueira#aol.com,Bianca Barros Rocha Torres Siqueira,PB/Cabedelo
7,8,pimentel.alves.luiz#outlook.com,Luiz Alves Pimentel,SE - Aracaju
8,9,lucas.lopes.guedes.cunha#tutanota.com,Lucas Guedes Cunha Lopes,PB - João Pessoa
9,10,paiva.débora#gmx.com,Débora Paiva,Santarém / PA
10,11,torres.monteiro.victor@gmail.com,Victor Torres Monteiro,BA - Porto Seguro
11,12,rafael.pereira.barros#zoho.com,Rafael Pereira Barros,"TO , Fortaleza do Tabocão"
12,13,martins.guimarães.carlos#hotmail.com,Carlos Guimarães Martins,PA / Santarém
13,14,vieira.silva.amaral.gabriela@icloud.com,Gabriela Silva Vieira Amaral,"AM , Itacoatiara"
14,15,lopes.alves.pacheco.rocha.carla#yahoo.com,Carla Lopes Alves Pacheco Rocha,"Fortaleza do Tabocão,TO"
15,16,renata.pacheco.cardoso@zoho.com,Renata Pacheco Cardoso,"Fortaleza,CE"
16,17,costa.paiva.luís.coelho.cardoso@aol.com,Luís Paiva Costa Cardoso Coelho,MS - Corumbá
17,18,rocha.adriana.guedes.borges.alves#protonmail.com,Adriana Guedes Borges Alves Rocha,Santarém - PA
18,19,renata.lima.mendonça.coelho.gomes@icloud.com,Renata Lima Gomes Coelho Mendonça,Maceió / AL
19,20,silva.bruno@zoho.com,Bruno Silva,"PA , Santarém Novo"
20,21,peixoto.soares.rocha.oliveira.sandra#yahoo.com,Sandra Rocha Oliveira Soares Peixoto,"AC,Rio Branco"
21,22,borges.vieira.daniela.mendonça.farias#protonma...,Daniela Borges Vieira Farias Mendonça,SE / Aracaju
22,23,rodrigues.mendonça.bruna#aol.com,Bruna Mendonça Rodrigues,Santos - SP
23,24,peixoto.carla.araújo.silva.azevedo#outlook.com,Carla Peixoto Azevedo Silva Araújo,Laguna / SC
24,25,femininos.antunes.amaral.lopes.ribeiro@icloud.com,Femininos Antunes Lopes Ribeiro Amaral,ES / São Mateus
25,26,gomes.araújo.borges.luiz#hotmail.com,Luiz Borges Gomes Araújo,Manaus/AM
26,27,nunes.flávia.coelho.martins.ribeiro@protonmail...,Flávia Nunes Martins Ribeiro Coelho,"Salvador,BA"
27,28,rodrigues.bianca@icloud.com,Bianca Rodrigues,"PR , Antonina"
28,29,moraes.nunes.gabriela.macedo@icloud.com,Gabriela Moraes Macedo Nunes,"CE,Fortaleza"
29,30,araújo.tavares.azevedo.victor.correia@gmail.com,Victor Araújo Azevedo Tavares Correia,Itacoatiara - AM
30,31,jéssica.martins.leite.figueiredo#tutanota.com,Jéssica Figueiredo Leite Martins,"São Luís,MA"
31,32,antunes.coelho.batista.teixeira.daniela@hotmai...,Daniela Teixeira Antunes Coelho Batista,BA - Porto Seguro
32,33,guedes.cunha.costa.diego#outlook.com,Diego Costa Guedes Cunha,Rio Grande/RS
33,34,nunes.cunha.victor.vieira#protonmail.com,Victor Vieira Nunes Cunha,Fortaleza / CE
34,35,martins.priscila#tutanota.com,Priscila Martins,João Pessoa / PB
35,36,ribeiro.francisca.pinheiro@aol.com,Francisca Ribeiro Pinheiro,Belém/PA
36,37,nunes.borges.teixeira.pimentel.jéssica#yahoo.com,Jéssica Pimentel Borges Nunes Teixeira,"MA , Itaqui (São Luís)"
37,38,mateus.antunes#gmail.com,Mateus Antunes,TO/Fortaleza do Tabocão
38,39,oliveira.renata.siqueira@aol.com,Renata Oliveira Siqueira,PE / Suape (Ipojuca)
39,40,pacheco.lucas#aol.com,Lucas Pacheco,"Corumbá,MS"
40,41,costa.correia.ribeiro.santos.pedro#yahoo.com,Pedro Ribeiro Costa Santos Correia,BA / Aratu (Candeias)
41,42,márcia.figueiredo#protonmail.com,Márcia Figueiredo,Vila do Conde (Barcarena) - PA
42,43,farias.jéssica.cunha@outlook.com,Jéssica Farias Cunha,MA/Itaqui (São Luís)
43,44,rafael.vieira.paiva#icloud.com,Rafael Paiva Vieira,Paranaguá / PR
44,45,figueiredo.siqueira.rodrigues.amanda.santos#tu...,Amanda Santos Figueiredo Rodrigues Siqueira,"Santarém,PA"
45,46,costa.farias.coelho.ana.silva#hotmail.com,Ana Silva Costa Farias Coelho,Macapá/AP
46,47,lacerda.gabriela.barros#tutanota.com,Gabriela Barros Lacerda,RJ / Niterói
47,48,torres.oliveira.peixoto.letícia@yahoo.com,Letícia Torres Peixoto Oliveira,PE - Suape (Ipojuca)
48,49,costa.tavares.antunes.diego#icloud.com,Diego Costa Tavares Antunes,SE/Aracaju

In [15]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df_clientes, title="Clientes Profiling", explorative=True)
profile.to_file("docs/profiling_clientes.html")

ModuleNotFoundError: No module named 'pkg_resources'

## EDA Custos
_________________________________________________________________________________________

In [3]:
df_custos

,category,historic_data,product_id,product_name
0,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 105...",1,Transponder AIS Maré Magnum
1,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 432...",2,Transponder Furuno Marlin
2,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 254...",3,Radar Furuno Pulse Leviathan
3,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909...",4,Rádio AIS Hydro Tidal Zen
4,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 600...",5,Piloto Automático Furuno Storm
...,...,...,...,...
145,ancoragem,"[{'start_date': '03/05/2016', 'usd_price': 139...",146,Corrente Delta Vox Ion
146,ancoragem,"[{'start_date': '13/05/2016', 'usd_price': 864...",147,Corrente Danforth Force Leviathan Impulse
147,ancoragem,"[{'start_date': '06/06/2017', 'usd_price': 145...",148,Âncora Delta Force Barracuda Mako
148,ancoragem,"[{'start_date': '19/02/2016', 'usd_price': 287...",149,Cabo de Nylon Bruce Core
149,ancoragem,"[{'start_date': '28/11/2018', 'usd_price': 426...",150,Cabo de Nylon Danforth Magnum Vox

In [4]:
df_produtos

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
...,...,...,...,...
152,Corrente Delta Vox Ion,R$ 495.98,146,ancoragem
153,Corrente Danforth Force Leviathan Impulse,R$ 3030.08,147,Ancoraguem
154,Âncora Delta Force Barracuda Mako,R$ 4785.56,148,Ancorajem
155,Cabo de Nylon Bruce Core,R$ 1163.62,149,Ancoragem
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,Ancorajem

In [5]:
df_vendas

          id  id_client  id_product   qtd      total   sale_date
0        0.0       42.0       105.0  11.0    3405.00  2023-09-10
1        1.0        3.0       136.0   9.0   16873.90  15-09-2024
2        2.0       25.0       139.0   7.0    9475.30  2024-08-13
3        4.0       20.0        23.0   5.0   55893.00  2023-02-03
4        5.0        8.0        57.0   4.0  451403.90  2024-02-12
...      ...        ...         ...   ...        ...         ...
9896  9995.0       30.0       139.0   6.0    8549.00  11-03-2023
9897  9996.0        9.0       111.0   7.0   28497.15  17-09-2023
9898  9997.0       38.0       123.0   2.0    5276.30  20-06-2023
9899  9998.0       33.0        97.0   6.0  771409.50  23-10-2024
9900  9999.0        8.0        20.0   6.0  185001.00  15-06-2023

[9901 rows x 6 columns]

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 348, in dispatch_control
    await self.process_control(msg)
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 354, in process_control
    idents, msg = self.session.feed_identities(msg, copy=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diomoura/projetos/Lighthouse/Lighthouse26/.venv/lib/python3.12/site-packages/jupyter_client/session.py", line 998, in feed_identities
    raise ValueError(msg)
ValueError: DELIM not in msg_list